framework:
  serializer: { enable_annotations: true }
  translator: { fallback: en }
  secret:          '%env(APP_SECRET)%'
  form:            ~
  csrf_protection: ~
  validation:      { enabled: true, enable_annotations: true }
  default_locale:  '%env(LOCALE)%'
  session:         ~
  fragments:       ~
  assets:
    version_strategy: 'catrobat.versioning'
    json_manifest_path: null