framework:
  serializer: { enable_annotations: true }
  translator: { fallback: en }
  secret:          "%secret%"
  form:            ~
  csrf_protection: ~
  validation:      { enabled: true, enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  session:         ~
  fragments:       ~
  assets:
    version: '%env(string:APP_VERSION)%'
