# Sonata Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.stats:
            contexts: [admin]
        sonata.admin.block.admin_list:
            contexts:  [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

sonata_admin:
    title:     Admin Panel
    title_logo: images/admin/admin_logo.png
    show_mosaic_button: false
    templates:
        layout: 'Admin\standard_layout.html.twig'
    dashboard:
        blocks:
#            -  # Not needed since we use the sidebar
#                position: left
#                type: sonata.admin.block.admin_list

            -  # Welcome Greeting
                position: center
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Admin Panel!</h2>
                        According to your role you can access different information and tools.
                        <br><br>

            -  # All Programs block
                class:    col-lg-3 col-xs-6
                position: bottom
                type:     sonata.admin.block.stats
                settings:
                    code: catrowebadmin.block.programs.all
                    icon: fa-cubes
                    text: All projects
                    color: bg-blue


            -  # Programs Approve
                class:    col-lg-3 col-xs-6
                position: bottom
                type:     sonata.admin.block.stats
                settings:
                    code: catrowebadmin.block.programs.approve
                    icon: fa-warning
                    text: Unapproved projects
                    color: bg-yellow

            -  # Reported Programs
                class:    col-lg-3 col-xs-6
                position: bottom
                type:     sonata.admin.block.stats
                settings:
                    code: catrowebadmin.block.programs.reported
                    icon: fa-bullhorn
                    text: Reported projects
                    color: bg-red
                    filters:
                        state: { type: 3, value: 1 } # 3 => NumberType::TYPE_EQUAL

            -  # User
                class:    col-lg-3 col-xs-6
                position: bottom
                type:     sonata.admin.block.stats
                settings:
                    code: catrowebadmin.block.users.user
                    icon: fa-users
                    text: User
                    color: bg-green

            # - { position: right, type: catrowebadmin.block.tools.statistic}


        groups:

            sonata.admin.group.programs:
                label:           Projects
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-cubes"></i>'
                items:
                    - catrowebadmin.block.programs.all
                    - catrowebadmin.block.programs.approve
                    - catrowebadmin.block.programs.reported
                    - catrowebadmin.block.programs.comments

            sonata.admin.group.featured:
                label:           Special Projects
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-bullhorn"></i>'
                items:
                    - catrowebadmin.block.programs.categories
                    - catrowebadmin.block.featured.program
                    - catrowebadmin.block.programs.templates
                    - catrowebadmin.block.example.program


            sonata.admin.group.mediapackage:
                label:           Media Package
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-newspaper-o"></i>'
                items:
                    - catrowebadmin.block.mediapackage.package
                    - catrowebadmin.block.mediapackage.category
                    - catrowebadmin.block.mediapackage.file

            sonata.admin.group.apk:
                label:           Apk Generation
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-android"></i>'
                items:
                    - catrowebadmin.block.apk.pending
                    - catrowebadmin.block.apk.list

            sonata.admin.group.users:
                label:           Users
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-users"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - catrowebadmin.block.users.limited
                    - catrowebadmin.block.users.storeduserdata
                    - catrowebadmin.block.users.reported

            sonata.admin.group.tools:
                label:           Tools
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - catrowebadmin.block.tools.maintain
                    - catrowebadmin.block.tools.logs
                    - catrowebadmin.block.tools.rudewords
                    - catrowebadmin.block.tools.notify
                    - catrowebadmin.block.tools.gcm
                    - catrowebadmin.block.tools.broadcast
                    - catrowebadmin.block.tools.mail

            sonata.admin.group.gamejams:
                label:           GameJam
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - catrowebadmin.block.gamejam
                    - catrowebadmin.block.program.snapshots

            sonata.admin.group.extensions:
                label:           Extensions
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-external-link"></i>'
                items:
                    - catrowebadmin.block.extensions.all
                    - catrowebadmin.block.extensions.create

            sonata.admin.group.statistics:
                label:           Statistics
                label_catalogue: Catrobat
                icon:            '<i class="fa fa-bar-chart"></i>'
                items:
                    - catrowebadmin.block.statistics.programs
                    - catrowebadmin.block.statistics.clicks

    security:

        handler: sonata.admin.security.handler.acl

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]


sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

    templates:
        form:
            - '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'
        filter:
            - '@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig'
        types:
            list:
                array:     '@SonataAdmin/CRUD/list_array.html.twig'
                boolean:   '@SonataAdmin/CRUD/list_boolean.html.twig'
                date:      '@SonataAdmin/CRUD/list_date.html.twig'
                time:      '@SonataAdmin/CRUD/list_time.html.twig'
                datetime:  '@SonataAdmin/CRUD/list_datetime.html.twig'
                text:      '@SonataAdmin/CRUD/base_list_field.html.twig'
                trans:     '@SonataAdmin/CRUD/list_trans.html.twig'
                string:    '@SonataAdmin/CRUD/base_list_field.html.twig'
                smallint:  '@SonataAdmin/CRUD/base_list_field.html.twig'
                bigint:    '@SonataAdmin/CRUD/base_list_field.html.twig'
                integer:   '@SonataAdmin/CRUD/base_list_field.html.twig'
                decimal:   '@SonataAdmin/CRUD/base_list_field.html.twig'
                identifier: '@SonataAdmin/CRUD/base_list_field.html.twig'

            show:
                array:     '@SonataAdmin/CRUD/show_array.html.twig'
                boolean:   '@SonataAdmin/CRUD/show_boolean.html.twig'
                date:      '@SonataAdmin/CRUD/show_date.html.twig'
                time:      '@SonataAdmin/CRUD/show_time.html.twig'
                datetime:  '@SonataAdmin/CRUD/show_datetime.html.twig'
                text:      '@SonataAdmin/CRUD/base_show_field.html.twig'
                trans:     '@SonataAdmin/CRUD/show_trans.html.twig'
                string:    '@SonataAdmin/CRUD/base_show_field.html.twig'
                smallint:  '@SonataAdmin/CRUD/base_show_field.html.twig'
                bigint:    '@SonataAdmin/CRUD/base_show_field.html.twig'
                integer:   '@SonataAdmin/CRUD/base_show_field.html.twig'
                decimal:   '@SonataAdmin/CRUD/base_show_field.html.twig'

sonata_user:
    security_acl:  true
    manager_type:  orm
    class:
        user:   App\Entity\User
        group:  App\Entity\Group

    admin:                  # Admin Classes
        user:
            class:          App\Admin\UserAdmin
            translation:    SonataUserBundle