parameters:
#    catrobat_admin.example.class: Catrobat\AdminBundle\Example

services:
      catrowebadmin.command.init:
              class: Catrobat\AdminBundle\Command\InitDirectoriesCommand
              arguments: ["@catrowebadmin.filesystem","%catrobat.file.storage.dir%"]
              calls:
                - [setProgramfileDirectory, ["%catrobat.file.storage.dir%"]]
                - [setExtractDirectory, ["%catrobat.file.extract.dir%"]]
                - [setScreenshotDirectory, ["%catrobat.screenshot.dir%"]]
                - [setThumbnailDirectory, ["%catrobat.thumbnail.dir%"]]
              tags:
                -  { name: console.command }

      catrowebadmin.command.import:
              class: Catrobat\AdminBundle\Command\ProgramImportCommand
              arguments: ["@catrowebadmin.filesystem","@catrobat.core.model.usermanager","@catrobat.core.model.programmanager"]
              tags:
                -  { name: console.command }

      catrowebadmin.filesystem:
              class: Symfony\Component\Filesystem\Filesystem
              public: false

      catrowebadmin.block.all_programs:
        class: Catrobat\AdminBundle\Admin\AllProgramsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Programs, label: All Programs }
        arguments: [null, Catrobat\CoreBundle\Entity\Program, null]

      catrowebadmin.block.approve_programs:
        class: Catrobat\AdminBundle\Admin\ApproveProgramsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Programs, label: Approve Programs }
        arguments: [null, Catrobat\CoreBundle\Entity\Program, null]

      catrowebadmin.block.notify_upload_programs:
        class: Catrobat\AdminBundle\Admin\UploadNotificationAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Tools, label: Upload Notify }
        arguments: [null, Catrobat\CoreBundle\Entity\User, null]