#fos_js_routing:
#    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

translate:
    path:  /translate/{word}/{array}/{domain}
    controller: App\Catrobat\Controller\Web\TranslationController:translateAction
    defaults:
        array: ""
        domain: "catroweb"
    options:
        expose: true

edit_program_description:
    path:  /editProjectDescription/{id}/{newDescription}
    controller: App\Catrobat\Controller\Web\ProgramController:editProgramDescription
    options:
        expose: true

edit_program_credits:
    path: /editProjectCredits/{id}/{newCredits}
    controller: App\Catrobat\Controller\Web\ProgramController:editProgramCredits
    options:
        expose: true

api_media_lib_package_bynameurl:
    path: /{flavor}/api/media/packageByNameUrl/{package}/json
    controller: App\Catrobat\Controller\Api\MediaPackageController:getMediaFilesForPackageByNameUrl
    options:
        expose: true
