services:
      catroweb.file.validator.name:
            class: Catrobat\CoreBundle\Listeners\NameValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.description:
            class: Catrobat\CoreBundle\Listeners\DescriptionValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.filestructure:
            class: Catrobat\CoreBundle\Listeners\FileStructureValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert, priority: 250 }

      catroweb.file.validator.definedimages:
            class: Catrobat\CoreBundle\Listeners\OnlyDefinedImagesValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.xmlfile:
            class: Catrobat\CoreBundle\Listeners\XmlFileValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }
            
      catrobat.core.services.invalidprogramuploadlogger:
              class:        Catrobat\CoreBundle\Listeners\InvalidProgramUploadLogger
              arguments:    ["@logger"]
              tags:
                  - { name: monolog.logger, channel: upload }
                  - { name: kernel.event_listener, event: catrobat.program.invalid.upload, method: onInvalidProgramUploadedEvent }
