services:
      catrowebadmin.filesystem:
              class: Symfony\Component\Filesystem\Filesystem
              public: false


      catrowebadmin.command.clean.apk:
              class: Catrobat\AppBundle\Commands\CleanApkCommand
              tags:
                -  { name: console.command }

      catrowebadmin.command.clean.backup:
              class: Catrobat\AppBundle\Commands\CleanBackupsCommand
              tags:
                -  { name: console.command }

      catrowebadmin.command.clean.extracted:
              class: Catrobat\AppBundle\Commands\CleanExtractedFileCommand
              tags:
                -  { name: console.command }

      catrowebadmin.command.init:
              class: Catrobat\AppBundle\Commands\InitDirectoriesCommand
              arguments: ["@catrowebadmin.filesystem","%catrobat.file.storage.dir%"]
              calls:
                - [setProgramfileDirectory, ["%catrobat.file.storage.dir%"]]
                - [setExtractDirectory, ["%catrobat.file.extract.dir%"]]
                - [setScreenshotDirectory, ["%catrobat.screenshot.dir%"]]
                - [setThumbnailDirectory, ["%catrobat.thumbnail.dir%"]]
                - [setMediaPackageDirectory, ["%catrobat.mediapackage.dir%"]]
              tags:
                -  { name: console.command }

      catrowebadmin.command.import:
              class: Catrobat\AppBundle\Commands\ProgramImportCommand
              arguments: ["@catrowebadmin.filesystem","@usermanager","@programmanager"]
              tags:
                -  { name: console.command }

      catrowebadmin.command.refresh:
              class: Catrobat\AppBundle\Commands\RefreshCommand
              arguments: ["@catrowebadmin.filesystem"]
              tags:
                -  { name: console.command }

      catrowebadmin.command.drop.migration:
              class: Catrobat\AppBundle\Commands\DropMigrationCommand
              arguments: ["@migrationmanager"]
              tags:
                - { name: console.command }

      command.reset:
              class: Catrobat\AppBundle\Commands\ResetCommand
              tags:
                -  { name: console.command }

      command.purge:
              class: Catrobat\AppBundle\Commands\PurgeCommand
              tags:
                -  { name: console.command }

      command.backup.create:
              class: Catrobat\AppBundle\Commands\CreateBackupCommand
              tags:
                -  { name: console.command }

      command.backup.restore:
              class: Catrobat\AppBundle\Commands\RestoreBackupCommand
              tags:
                -  { name: console.command }


      catrowebadmin.command.import.legacy:
              class: Catrobat\AppBundle\Commands\ImportLegacyCommand
              arguments: ["@catrowebadmin.filesystem","@usermanager","@programmanager", "@doctrine.orm.entity_manager"]
              tags:
                -  { name: console.command }

      catrowebadmin.create.constant.tags:
              class: Catrobat\AppBundle\Commands\CreateConstantTagsCommand
              arguments: ["@doctrine.orm.entity_manager", "@translator"]
              tags:
                -  { name: console.command }

      catrowebadmin.create.program.extensions:
              class: Catrobat\AppBundle\Commands\CreateProgramExtensionsCommand
              arguments: ["@doctrine.orm.entity_manager", "%catrobat.file.storage.dir%", "@programrepository"]
              tags:
                -  { name: console.command }