parameters:
      catrobat.webdir:                "%kernel.root_dir%/../web/"
      catrobat.resources.dir:         "%kernel.root_dir%/../web/resources/"
      catrobat.file.extract.dir:      "%kernel.root_dir%/../web/resources/extract/"
      catrobat.file.extract.path:     "resources/extract/"
      catrobat.file.storage.dir:      "%kernel.root_dir%/../web/resources/programs/"
      catrobat.file.storage.path:     "resources/programs/"
      catrobat.template.storage.dir:  "%kernel.root_dir%/../web/resources/templates/"
      catrobat.template.storage.path: "resources/templates/"
      catrobat.screenshot.dir:        "%catrobat.webdir%resources/screenshots/"
      catrobat.screenshot.path:       "resources/screenshots/"
      catrobat.template.dir:          "%catrobat.webdir%resources/templates/"
      catrobat.template.path:         "resources/templates/"
      catrobat.template.screenshot.dir:        "%catrobat.webdir%resources/templates/screenshots/"
      catrobat.template.screenshot.path:       "resources/templates/screenshots/"
      catrobat.thumbnail.dir:         "%catrobat.webdir%resources/thumbnails/"
      catrobat.thumbnail.path:        "resources/thumbnails/"
      catrobat.template.thumbnail.dir:         "%catrobat.webdir%resources/templates/thumbnails/"
      catrobat.template.thumbnail.path:        "resources/templates/thumbnails/"
      catrobat.featuredimage.dir:     "%catrobat.webdir%resources/featured/"
      catrobat.featuredimage.path:    "resources/featured/"
      catrobat.mediapackage.dir:      "%catrobat.webdir%resources/mediapackage/"
      catrobat.mediapackage.path:     "resources/mediapackage/"
      catrobat.apk.dir:               "%catrobat.webdir%resources/apk/"
      catrobat.backup.dir:            "%kernel.root_dir%/../backups/"
      catrobat.snapshot.dir:          "%kernel.root_dir%/../Resources/Snapshots"
      catrobat.translations.dir:      "%kernel.root_dir%/Resources/translations"
      catrobat.logs.dir:              "%kernel.root_dir%/logs/"
      
services:


    apikey_authenticator:
        class:     Catrobat\AppBundle\Security\ApiKeyAuthenticator
        arguments: ["@translator"]

    user_authenticator:
        class: Catrobat\AppBundle\Security\UserAuthenticator
        arguments: ["@security.user.provider.concrete.chain_provider","@security.authentication.manager"]


    template_service:
        class: Catrobat\AppBundle\Services\TemplateService
        arguments:
          - "@templatemanager"
# =========================== Repository ===========================

    programrepository:
        class: Catrobat\AppBundle\Entity\ProgramRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:Program"

    programlikerepository:
        class: Catrobat\AppBundle\Entity\ProgramLikeRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:ProgramLike"

    programremixrepository:
        class: Catrobat\AppBundle\Entity\ProgramRemixRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:ProgramRemixRelation"

    programremixbackwardrepository:
        class: Catrobat\AppBundle\Entity\ProgramRemixBackwardRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:ProgramRemixBackwardRelation"

    scratchprogramrepository:
        class: Catrobat\AppBundle\Entity\ScratchProgramRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:ScratchProgram"

    scratchprogramremixrepository:
        class: Catrobat\AppBundle\Entity\ScratchProgramRemixRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:ScratchProgramRemixRelation"

    userlikesimilarityrelationrepository:
        class: Catrobat\AppBundle\Entity\UserLikeSimilarityRelationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:UserLikeSimilarityRelation"

    userremixsimilarityrelationrepository:
        class: Catrobat\AppBundle\Entity\UserRemixSimilarityRelationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:UserRemixSimilarityRelation"

    tagrepository:
        class: Catrobat\AppBundle\Entity\TagRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:Tag"

    extensionrepository:
        class: Catrobat\AppBundle\Entity\ExtensionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:Extension"

    notificationrepository:
        class: Catrobat\AppBundle\Entity\NotificationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle:Notification"]

    rudewordrepository:
        class: Catrobat\AppBundle\Entity\RudeWordsRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:RudeWord"

    gamejamrepository:
        class: Catrobat\AppBundle\Entity\GameJamRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:GameJam"

    featuredrepository:
        class: Catrobat\AppBundle\Entity\FeaturedRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:FeaturedProgram"

    filerepository:
        class: Catrobat\AppBundle\Services\ProgramFileRepository
        arguments: ["%catrobat.file.storage.dir%","%catrobat.file.storage.path%", "@filecompressor"]

    extractedfilerepository:
        class: Catrobat\AppBundle\Services\ExtractedFileRepository
        arguments:
            - "%catrobat.file.extract.dir%"
            - "%catrobat.file.extract.path%"
            - "%catrobat.file.storage.dir%"
            - "@fileextractor"
            - "@programmanager"
            - "@filerepository"

    screenshotrepository:
        class: Catrobat\AppBundle\Services\ScreenshotRepository
        arguments: ["%catrobat.screenshot.dir%","%catrobat.screenshot.path%","%catrobat.thumbnail.dir%","%catrobat.thumbnail.path%"]

    templatescreenshotrepository:
            class: Catrobat\AppBundle\Services\ScreenshotRepository
            arguments: ["%catrobat.template.screenshot.dir%","%catrobat.template.screenshot.path%","%catrobat.template.thumbnail.dir%","%catrobat.template.thumbnail.path%"]

    featuredimagerepository:
        class: Catrobat\AppBundle\Services\FeaturedImageRepository
        arguments: ["%catrobat.featuredimage.dir%","%catrobat.featuredimage.path%"]

    mediapackagefilerepository:
        class: Catrobat\AppBundle\Services\MediaPackageFileRepository
        arguments: ["%catrobat.mediapackage.dir%","%catrobat.mediapackage.path%"]

    apkrepository:
        class: Catrobat\AppBundle\Services\ApkRepository
        arguments: ["%catrobat.apk.dir%"]

    backupfilerepository:
        class: Catrobat\AppBundle\Services\BackupFileRepository
        arguments: ["%catrobat.backup.dir%"]

    programdevicepermissionreader:
        class: Catrobat\AppBundle\Services\ProgramDevicePermissionReader

    templaterepository:
        class: Catrobat\AppBundle\Entity\TemplateRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:Template"

    templatefilerepository:
            class: Catrobat\AppBundle\Services\TemplateFileRepository
            arguments: ["%catrobat.template.storage.dir%","%catrobat.template.storage.path%", "@filecompressor"]
# =========================== Manager & Stuff ===========================

    programmanager:
        class: Catrobat\AppBundle\Entity\ProgramManager
        arguments: 
            - "@fileextractor"
            - "@filerepository"
            - "@screenshotrepository"
            - "@doctrine.orm.entity_manager"
            - "@programrepository"
            - "@tagrepository"
            - "@programlikerepository"
            - "@event_dispatcher"


    templatemanager:
        class: Catrobat\AppBundle\Entity\TemplateManager
        arguments:
            - "@templatefilerepository"
            - "@templatescreenshotrepository"
            - "@doctrine.orm.entity_manager"
            - "@templaterepository"

    programmanager.remix_manipulation:
        class: Catrobat\AppBundle\Commands\RemixManipulationProgramManager
        arguments:
            - "@fileextractor"
            - "@filerepository"
            - "@screenshotrepository"
            - "@doctrine.orm.entity_manager"
            - "@programrepository"
            - "@tagrepository"
            - "@programlikerepository"
            - "@event_dispatcher"

    remixmanager:
        class: Catrobat\AppBundle\Entity\RemixManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@programrepository"
            - "@scratchprogramrepository"
            - "@programremixrepository"
            - "@programremixbackwardrepository"
            - "@scratchprogramremixrepository"
            - "@remixgraphmanipulator"

    remixgraphmanipulator:
        class: Catrobat\AppBundle\RemixGraph\RemixGraphManipulator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@remixsubgraphmanipulator"
            - "@programremixrepository"
            - "@programremixbackwardrepository"
            - "@scratchprogramremixrepository"

    remixsubgraphmanipulator:
        class: Catrobat\AppBundle\RemixGraph\RemixSubgraphManipulator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@programrepository"
            - "@programremixrepository"
            - "@programremixbackwardrepository"

    migrationmanager:
        class: Catrobat\AppBundle\Entity\MigrationManager
        arguments:
         - "@doctrine.orm.entity_manager"

    recommendermanager:
        class: Catrobat\AppBundle\RecommenderSystem\RecommenderManager
        arguments:
         - "@doctrine.orm.entity_manager"
         - "@usermanager"
         - "@userlikesimilarityrelationrepository"
         - "@userremixsimilarityrelationrepository"
         - "@programlikerepository"
         - "@programremixrepository"
         - "@programremixbackwardrepository"

    rudewordfilter:
        class: Catrobat\AppBundle\Services\RudeWordFilter
        arguments: ["@rudewordrepository"]

    usermanager:
        class: Catrobat\AppBundle\Entity\UserManager
        arguments: ["@security.encoder_factory","@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager","%fos_user.model.user.class%"]

    usermanager.ldap:
        class: Catrobat\AppBundle\Entity\UserLDAPManager
        arguments:
            - "@fr3d_ldap.ldap_driver"
            - "@fr3d_ldap.user_manager"
            - %fr3d_ldap.ldap_manager.parameters%
            - %ldap_role_mappings%
            - %ldap_group_filter%
            - "@tokengenerator"
            - "@logger"

    fileextractor:
        class: Catrobat\AppBundle\Services\CatrobatFileExtractor
        arguments: ["%catrobat.file.extract.dir%","%catrobat.file.extract.path%"]

    filecompressor:
        class: Catrobat\AppBundle\Services\CatrobatFileCompressor

    tokengenerator:
        class: Catrobat\AppBundle\Services\TokenGenerator

    time:
        class: Catrobat\AppBundle\Services\Time

    elapsedtime:
        class: Catrobat\AppBundle\Services\Formatter\ElapsedTimeStringFormatter
        arguments: ["@translator","@time"]

# =========================== Twig ===========================

    app.twig_extension:
        class: Catrobat\AppBundle\Twig\AppExtension
        public: false
        arguments: ["@request_stack", "@mediapackagefilerepository", "@gamejamrepository", "@liip_theme.active_theme", "%catrobat.translations.dir%", "@service_container"]
        tags:
            - { name: twig.extension }

# =========================== Jenkins ===========================

    ci.jenkins.dispatcher:
        class: Catrobat\AppBundle\Services\Ci\JenkinsDispatcher
        arguments: 
          - "@router" 
          - "%jenkins%"
          
# =========================== Controller ===========================

    controller.upload:
        class: Catrobat\AppBundle\Controller\Api\UploadController
        arguments:
          - "@usermanager"
          - "@security.token_storage"
          - "@programmanager"
          - "@gamejamrepository"
          - "@tokengenerator"
          - "@translator"

# =========================== Social ===========================

    facebook_post_service:
        class: Catrobat\AppBundle\Services\FacebookPostService
        arguments: ["@router", "@service_container", "@screenshotrepository"]

    oauth_service:
        class: Catrobat\AppBundle\Services\OAuthService
        arguments:
          - "@service_container"
# =========================== Download ===========================

    statistics:
        class: Catrobat\AppBundle\Services\StatisticsService
        arguments:
          - "@programmanager"
          - "@doctrine.orm.entity_manager"
          - "@bazinga_geocoder.geocoder"
          - "@logger"
          - "@security.token_storage"
        tags:
          - { name: monolog.logger, channel: download_stats }


# =========================== Async HTTP Client ===========================
    async_http_client:
        class: Catrobat\AppBundle\Services\AsyncHttpClient
        arguments:
          - { timeout: 8.0, max_number_of_total_requests: 12, max_number_of_concurrent_requests: 4 }
