catrobat_web_index:
    path: /
    defaults: { _controller: "catrobat.web.default.controller:indexAction" }

catrobat_web_index_locale:
    path: /{_locale}/
    defaults: { _controller: "catrobat.web.default.controller:indexAction", _locale: en }
    requirements:
        _locale:  en|de    

catrobat_web_program:
    path:      /program/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.default.controller:programAction" }
    requirements:
      id:  \d+

catrobat_web_search:
    path:     /search/{q}
    methods:  [GET]
    defaults: { _controller: "catrobat.web.default.controller:searchAction" }
    requirements:
      q: .+

catrobat_web_search_nothing:
    path:     /search/
    methods:  [GET]
    defaults: { _controller: "catrobat.web.default.controller:searchNothingAction" }

catrobat_web_profile:
    path:      /profile/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.default.controller:profileAction" }
    requirements:
      id:  \d+

catrobat_web_tutorial:
    path:      /tutorial
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.tutorial.controller:tutorialAction" }

catrobat_web_tutorials:
    path:      /tutorial/tutorials
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.tutorial.controller:tutorialsAction" }

catrobat_web_stepByStep:
    path:      /tutorial/stepByStep
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.tutorial.controller:stepByStepAction" }

catrobat_web_starter:
    path:      /tutorial/starterPrograms
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.tutorial.controller:starterProgramsAction" }

catrobat_web_termsOfUse:
    path:      /termsOfUse
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.default.controller:termsOfUseAction" }

catrobat_web_licenseToPlay:
    path:      /licenseToPlay
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.default.controller:licenseToPlayAction" }

# Same as /programs ... just for compatibility reason again with /details
catrobat_web_detail:
    path:      /details/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.default.controller:programAction" }
    requirements:
      id:  \d+
