
name: Feature Requests

on:
  #
  # This category of tests should not block the merging process due to a failed pipeline.
  # This tests are somewhat "independent" of the actual changes a developer made and therefore must not run on a PR
  #
  push:
    branches:
      - master
      - develop
  release:
    types:
      - created

jobs:

  check_for_new_catroid_blocks:
    name: Check for new Catroid Blocks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        run: |
          sudo apt-get install php

      - name: Set Permissions
        run: |
          sudo chmod 777 bin/checkCatroidRepositoryForNewBricks

      - name: Check Catroid Repository for new bricks
        run: |
          bin/checkCatroidRepositoryForNewBricks